# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=15)),
                ('contrasena', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=15)),
                ('contrasena', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=10)),
                ('nombre_de_negocio', models.CharField(max_length=45)),
                ('cantidad', models.IntegerField()),
                ('tamano', models.CharField(choices=[('0', 'cuarto de oficio'), ('1', 'media carta'), ('2', 'carta'), ('3', 'oficio')], default='0', max_length=1)),
                ('tipo_papel', models.CharField(choices=[('0', 'normal'), ('1', 'sensibilizado')], default='0', max_length=1)),
                ('precio', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='bus',
        ),
        migrations.DeleteModel(
            name='Bus',
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
    ]
